### ISSUE TITLE
 Unable to compile due to usage of unstable inspect method

### ISSUE THREAD

**Issue by pionoor** [cloudwego/sonic-rs#103]
**Description**:
I encountered an issue while attempting to compile the project. The compilation fails due to the use of the unstable inspect method on Option/Result, which is currently only available in the nightly version of Rust.

**Steps to Reproduce**:

	1.	Clone the repository.
	2.	Attempt to compile the project using the stable Rust toolchain (e.g., rustc 1.70.0).
	3.	Observe the compilation error.
	
**Error Message:**
`error[E0658]: use of unstable library feature 'result_option_inspect'
  --> src/reader.rs:73:21
   |
73 |         self.peek().inspect(|_| {
   |                     ^^^^^^^
   |
   = note: see issue #91345 <https://github.com/rust-lang/rust/issues/91345> for more information`
   
**Expected Behavior:**
The project should compile successfully on the stable version of Rust.

**Environment:**

	•	Rust Version: stable 1.70.0 (or your current stable version)
	•	OS: [Your OS here, e.g., macOS Monterey 12.6.1]

**Comment by liuq19** [comment]
this feature is stable https://github.com/rust-lang/rust/pull/116866, pls update rustc version
