### ISSUE TITLE
[Question] how to manually get essential host info instead of `-C target-cpu=native`

### ISSUE THREAD

**Issue by wbprime** [cloudwego/sonic-rs#146]
**Is your feature request related to a problem? Please describe.**

It is adviced to add `-C target-cpu=native` flags when build crates using sonic-rs.

The idea behind was that the running/production host is the same with the building/dev host.

When the production host is not under control (say controlled by a dedicated ops team), how to get essential info to build crates.

1. the production host can not access the public net
2. hard to request ops team run build-time command (cargo ...)

Does there exist some tips to query essential info to achive the same effect as `-C target-cpu=native` does ?

**Describe the solution you'd like**

Provide some commands or instructions to collect essential info to achive the same effect as `-C target-cpu=native` does.

**Describe alternatives you've considered**

Provide some tricks to perpsuade ops team members to help collect host native info.

**Additional context**

None.

**Comment by liuq19** [comment]
We will support runtime detection, and will not need to add `-C target-cpu=native`.

 related issue #14
