### ISSUE TITLE
Attempt to subtract with overflow in number parsing

### ISSUE THREAD

**Issue by Shnatsel** [cloudwego/sonic-rs#17]
**Describe the bug**

Parsing the following input causes an attempt to subtract with overflow in `src/util/num/mod.rs:287:56`. This causes a panic in debug mode, but is silently ignored in release mode. The input that triggers it is:

```
[-0.31,-0.000000000000000000000000000000014,
-9223372036854775808
```

This happens because `-9223372036854775808` is the exact minimum number representable in an `i64`; however, the negation of it, +9223372036854775808, is not representable - it is one bigger than the representable maximum, 9223372036854775807.

The issue was discovered by the fuzzer. Here is the exact input the fuzzer has discovered, as a file: 
[sonic-subtract-overflow.json](https://github.com/cloudwego/sonic-rs/files/13056259/sonic-subtract-overflow.json)

**To Reproduce**

`cargo +nightly fuzz run fuzz_value sonic-subtract-overflow.json`

**Expected behavior**

Either the overflow is deemed to be expected and `.wrapping_sub()` is used instead of the `-` operator, or the logic issue causing the overflow is fixed.

**sonic-rs version:**

git master on commit 631411b83b07ccb9c570c15a8caa2269ad6b8762

**Environment:**

rustc 1.74.0-nightly (8550f15e1 2023-08-27)
binary: rustc
commit-hash: 8550f15e148407159af401e02b1d9259762b3496
commit-date: 2023-08-27
host: x86_64-unknown-linux-gnu
release: 1.74.0-nightly
LLVM version: 17.0.0

**Comment by liuq19** [comment]
Thanks, we will fix it later.
