### ISSUE TITLE
Using sonic-rs without UTF-8 validation can cause undefined behavior such as OOB reads

### ISSUE THREAD

**Issue by hkratz** [cloudwego/sonic-rs#20]
**Describe the bug**

Rust Strings have to be [always valid UTF-8](https://doc.rust-lang.org/std/string/struct.String.html#utf-8). Using `sonic_rs` withou validation turned on can return Strings containing invalid UTF-8. Those strings can cause segfaults due to OOB reads in other code which rely on this guarantee. This can cause many security issues.

There are three ways to solve this:
1. Make `from_slice` unsafe and place the burden on the caller to supply valid UTF-8 or
2. turn on UTF-8 validation unconditionally or
3. validate before creating Strings.

**To Reproduce**

1. Run the following code
```rs
use sonic_rs::from_slice;

fn main() {
    let json = b"\"abc\xff\"";
    let invalid_string: String = from_slice(json).unwrap();
    invalid_string.chars().for_each(|c| println!("{}", c));
}
```

**Expected behavior**

`from_slice` should return an error instead of an invalid String.

**Actual behavior**
```
 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/sonictest`
a
b
c
fish: Job 1, 'cargo run' terminated by signal SIGTRAP (Trace or breakpoint trap)
```
**sonic-rs version:**

0.1.3, default features

**Environment:**

MacOS, but similar behavior everywhere

**Comment by liuq19** [comment]
You could enable the `utf8` feature when needing the utf-8 validation

**Comment by PureWhiteWu** [comment]
Maybe we should rename this feature to "validate-utf8"?
I think this name is better than only "utf8", since this name can express a clearer meaning.

**Comment by hkratz** [comment]
> You could enable the `utf8` feature when needing the utf-8 validation
> 
> `sonic-rs = { version = "0.1.3", features = [ "utf8" ] }`

I know that this. Still you are breaking Rust safety guarantees with default features by creating invalid strings in safe Rust code. This is never OK for a safe API because other code relies on those safety guarantees as demonstrated.

**Comment by PureWhiteWu** [comment]
Maybe there's another choice that we can provide something like `unsafe fn from_slice_unchecked`? @liuq19

**Comment by liuq19** [comment]
We will add `unsafe fn from_slice_unchecked` apis and bump version `0.2.0`

**Comment by petermorrys** [comment]
Are you the founder of AIDE sir Hans Kratz

**Comment by petermorrys** [comment]
@hkratz I was busy waiting for AIDE Update even posting on your email but no reply am a big fan of AIDE and X-Develop from 2012 will use to chat on twitter on how to improve AIDE sir please what is the problem

**Comment by PureWhiteWu** [comment]
0.2.0 has been released.
If you have time, can you recheck if this has been fixed? @hkratz
