### ISSUE TITLE
`sonic_rs::to_{writer, writer_pretty}` over arbitrary I/O writers

### ISSUE THREAD

**Issue by aumetra** [cloudwego/sonic-rs#54]
**Is your feature request related to a problem? Please describe.**

It would be great if the `sonic_rs::to_{writer, writer_pretty}` could be used with arbitrary I/O writers.  
In particular, I'm attempting to implement a trait which only receives an `io::Write` type and I would like to serialize the JSON directly into the writer without any intermediate buffering.

**Describe the solution you'd like**

Any type that implements `std::io::Writer` can be used with `sonic_rs::to_{writer, writer_pretty}`

**Describe alternatives you've considered**

Write a wrapper struct that implements `WriteExt` but I'm not sure how to implement the trait for arbitrary writers

**Comment by liuq19** [comment]
Thanks, maybe we need `GrowedBufWriter<W: Write>` as a wrapper with `WriteExt` trait to fix the problem?
