### ISSUE TITLE
Benchmark on rust_serialization_benchmark

### ISSUE THREAD

**Issue by godofdream** [cloudwego/sonic-rs#58]
There is a benchmark repository which contains multiple json implementations:
https://github.com/djkoloski/rust_serialization_benchmark

It would make sense to add sonic-rs to that benchmark to be better compareable with other implementations like simd-json

**Comment by liuq19** [comment]
We use the [serde-rs benchmark ](https://github.com/serde-rs/json-benchmark)  now. 

We welcome to compare performance with any JSON. And I do not have enough time to support it. 

We will support it in the future :)
