### ISSUE TITLE
bump allocator with `Sync` and lock-free

### ISSUE THREAD

**Issue by liuq19** [cloudwego/sonic-rs#59]

**Comment by eloff** [comment]
I have a lock-free arena allocator for Rust, it uses mmap/VirtualAlloc directly, but it wouldn't be hard to modify it to use std::alloc instead. I'd be happy to contribute that code if it interests you (you can use it as a guide if nothing else.)

**Comment by liuq19** [comment]
Thanks a lot, that is interesting, the allocator is open-source? could you share the crate? 

But, the code is changing and we will not need it sonic-rs 0.4.
