### ISSUE TITLE
Undefined Behaviour: This crate doesn't check for cpu flags

### ISSUE THREAD

**Issue by dev-ardi** [cloudwego/sonic-rs#74]
**Describe the bug**

This crate has UB on cpus without avx support

**To Reproduce**

`cargo +nightly miri run` on a function that has `sonic_rs::from_str`

**Expected behavior**

A panic if the target doesn't support avx
**Screenshots**
![image](https://github.com/cloudwego/sonic-rs/assets/47633543/146c9df0-98d4-4044-9253-7acf950e26a1)

**Comment by liuq19** [comment]
low-level SIMD instructions are not supported for MIRI, and the work is in progress. #61

**Comment by Nilstrieb** [comment]
If you implement feature detection correctly, Miri should report that it doesn't support avx and you can take the fallback path.
This crate is unsound when running on CPUs that don't support AVX, which exist

**Comment by liuq19** [comment]
> If you implement feature detection correctly, Miri should report that it doesn't support avx and you can take the fallback path. This crate is unsound when running on CPUs that don't support AVX, which exist

yes, there is a TODO here and I ignored it... I will fixed it...

https://github.com/cloudwego/sonic-rs/blob/main/src/util/arch/mod.rs#L2

**Comment by liuq19** [comment]
Fixed in v0.3.5
