### ISSUE TITLE
Add support for non UTF-8 json input

### ISSUE THREAD

**Issue by wbprime** [cloudwego/sonic-rs#75]
**Is your feature request related to a problem? Please describe.**

sonic-rs would fail if the input bytes contain non UTF-8 characters, even for `pub fn from_slice<'a, T>(json: &'a [u8])` function.  However, there exists cases bytes containning non UTF-8 json need serialize/deserialize support, typically encoding GBK/GB18030 in China.

**Describe the solution you'd like**

- add support for non UTF-8 encoded json bytes in `from_slice` function
- or drop `from_slice` function

**Describe alternatives you've considered**

N/A.

**Additional context**
N/A.

**Comment by PureWhiteWu** [comment]
Hello, according to the [json rfc](https://www.ietf.org/rfc/rfc4627.txt), unicode encoding is enforced.

![image](https://github.com/cloudwego/sonic-rs/assets/3314335/3797e96a-ace3-46bd-a705-e1b0ba2375cd)

Furthermore, does other json library such as `serde_json`, `simd_json` support non utf-8 input?

**Comment by wbprime** [comment]
@PureWhiteWu sorry for late reply.

`serde_json` can deserialize non UTF-8 bytes. `simd_json` not tested.

Aware your design principle to adhere to JSON std.  However, UTF-8 is not the only encoding impl of unicode.  Say, if UTF-16 support is on your roadmap, maybe other non unicode encoding support could be simply achieved with little effort I guess.

Moreover, JSON std suggests support non UTF-8 encoding as an impl extension.

Last words: GBK/GB18030 encoding is much like UTF-8 keeping compatible with ASCII making it easy to support.

Thanks

**Comment by liuq19** [comment]
> @PureWhiteWu sorry for late reply.
> 
> `serde_json` can deserialize non UTF-8 bytes. `simd_json` not tested.
> 
> Aware your design principle to adhere to JSON std. However, UTF-8 is not the only encoding impl of unicode. Say, if UTF-16 support is on your roadmap, maybe other non unicode encoding support could be simply achieved with little effort I guess.
> 
> Moreover, JSON std suggests support non UTF-8 encoding as an impl extension.
> 
> Last words: GBK/GB18030 encoding is much like UTF-8 keeping compatible with ASCII making it easy to support.
> 
> Thanks

Thanks, could you give a test case? I know `serde_json` will not fail when parsing invalid UTF-8 into bytes.

**Comment by wbprime** [comment]
@liuq19 See [this repository](https://github.com/wbprime/sonic-rs-issue-deserialize-GB18030-encoded-bytes) for your convenience.
